[toolchain]
channel = "{{channel}}"
profile = "minimal"
components = [
    "rustfmt",
    "clippy",
    "rust-analyzer",
{%- if toolchain == "nightly" %}
    # "miri",
    "rustc-codegen-cranelift-preview",
{%- endif %}
{%- if toolchain == "nightly" or os-arch contains "windows" %}
    "llvm-tools-preview",
{%- endif %}
]
