[alias]
debug = "build --profile debugger"
Build = "build --release"
B = "Build"
Run = "run --release"
R = "Run"



[build]
incremental = true
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "symbol-mangling-version=v0",
  "-C", "target-cpu=native",
  # TODO: move this into profile.release once cargo feature `profile-rustflags` becomes stable
  "-Z", "share-generics=y",
]


[profile.release]
opt-level = 3
incremental = false
codegen-units = 1
lto = "fat"
debug = false
panic = "abort"
strip = "debuginfo"

[profile.release.package."*"]
opt-level = 3


[profile.dev]
opt-level = 0
codegen-units = 256
lto = false
debug = 1

[profile.dev.package."*"]
opt-level = 3


[profile.bench]
codegen-units = 256


[profile.debugger]
inherits = "dev"
debug = 2


[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "linker=clang",
]
